# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01d8b12867188228feacd5a978a69d32ab4dae2bffd2f03819c6c9b6905e7542d38ce0aa439a75a7d0c9edc5586cb06a271e411b13ef6fff8dd48787c24db306

test:
  secret_key_base: b43c88ba813955b4060121c62ac9c3fd94ff9a19d1ee5a7dd6d88879fe34dd252cae9966d796b8a82ad8f19c239d989e2cb5392ff061db7787adb71f1ec850ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
